//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "donation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub year: String,
    pub amount: i64,
    pub branch_id: i32,
    pub donor_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::branch::Entity",
        from = "Column::BranchId",
        to = "super::branch::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Branch,
    #[sea_orm(
        belongs_to = "super::donor::Entity",
        from = "Column::DonorId",
        to = "super::donor::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Donor,
}

impl Related<super::branch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Branch.def()
    }
}

impl Related<super::donor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Donor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
