//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::branch::Entity as Branch;
pub use super::donation::Entity as Donation;
pub use super::donor::Entity as Donor;
pub use super::party::Entity as Party;
